package jjm.learn.book.sale.mapper;

import java.util.List;
import jjm.learn.book.sale.POJO.OwnerInformationPOJO;
import jjm.learn.book.sale.POJO.OwnerInformationPOJOExample;
import org.apache.ibatis.annotations.Param;

public interface OwnerInformationPOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int countByExample(OwnerInformationPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int deleteByExample(OwnerInformationPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int insert(OwnerInformationPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int insertSelective(OwnerInformationPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    List<OwnerInformationPOJO> selectByExample(OwnerInformationPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    OwnerInformationPOJO selectByPrimaryKey(Integer id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByExampleSelective(@Param("record") OwnerInformationPOJO record, @Param("example") OwnerInformationPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByExample(@Param("record") OwnerInformationPOJO record, @Param("example") OwnerInformationPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByPrimaryKeySelective(OwnerInformationPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owerinfo
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByPrimaryKey(OwnerInformationPOJO record);
}