package jjm.learn.book.sale.mapper;

import java.util.List;

import jjm.learn.book.sale.POJO.OwnerInformationPOJO;
import jjm.learn.book.sale.POJO.OwnerPassWordPOJO;
import jjm.learn.book.sale.POJO.OwnerPassWordPOJOExample;

import org.apache.ibatis.annotations.Param;

public interface OwnerPassWordPOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int countByExample(OwnerPassWordPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int deleteByExample(OwnerPassWordPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int insert(OwnerPassWordPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int insertSelective(OwnerPassWordPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    List<OwnerPassWordPOJO> selectByExample(OwnerPassWordPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    OwnerPassWordPOJO selectByPrimaryKey(Integer id);

    OwnerPassWordPOJO selectByOwnerId(Integer id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByExampleSelective(@Param("record") OwnerPassWordPOJO record, @Param("example") OwnerPassWordPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByExample(@Param("record") OwnerPassWordPOJO record, @Param("example") OwnerPassWordPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByPrimaryKeySelective(OwnerPassWordPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownerpwd
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    int updateByPrimaryKey(OwnerPassWordPOJO record);
}