package jjm.learn.book.sale.POJO;

public class OwnerPassWordPOJO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ownerpwd.id
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ownerpwd.password
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownerpwd.id
     *
     * @return the value of ownerpwd.id
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownerpwd.id
     *
     * @param id the value for ownerpwd.id
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownerpwd.password
     *
     * @return the value of ownerpwd.password
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownerpwd.password
     *
     * @param password the value for ownerpwd.password
     *
     * @mbggenerated Mon Dec 09 04:06:41 EST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}